-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 19:41:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dgt
-- -----------------------------------------------------
-- Dirección general de tráfico
DROP SCHEMA IF EXISTS `dgt` ;

-- -----------------------------------------------------
-- Schema dgt
--
-- Dirección general de tráfico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dgt` DEFAULT CHARACTER SET utf8 ;
USE `dgt` ;

-- -----------------------------------------------------
-- Table `dgt`.`coches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgt`.`coches` ;

CREATE TABLE IF NOT EXISTS `dgt`.`coches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(10) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL DEFAULT 'cuatro latas',
  `km` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dgt`.`multas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgt`.`multas` ;

CREATE TABLE IF NOT EXISTS `dgt`.`multas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` FLOAT NULL DEFAULT 50,
  `concepto` VARCHAR(255) NOT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_coche` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_multas_coches_idx` (`id_coche` ASC) VISIBLE,
  CONSTRAINT `fk_multas_coches`
    FOREIGN KEY (`id_coche`)
    REFERENCES `dgt`.`coches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
